services:
  - type: web
    name: linkedin-scraper
    env: docker
    plan: free
    repo: https://github.com/YOUR_USERNAME/linkedin-scraper
    branch: main
    autoDeploy: true
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
